[toolchain]
channel = "nightly-2023-11-20"
components = [ "rust-src", "rustfmt" ]
targets = [
    "thumbv7em-none-eabi",
    "thumbv7m-none-eabi",
    "thumbv6m-none-eabi",
    "thumbv7em-none-eabihf",
    "thumbv8m.main-none-eabihf",
    "wasm32-unknown-unknown",
]
# features = ["async_fn_in_trait", "const_fn_trait_bound", "const_trait_impl", "custom_test_frameworks", "default_alloc_error_handler", "dispatch_from_dyn", "doc_cfg", "doc_spotlight", "doc_spotlight"]
